# server
server:
  port: 8501

# spring配置
spring:
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Q-D37Sq*k61#yT_y
  # redis
  data:
    redis:
      host: localhost
      port: 6379

# 自定义配置
eshop:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/getCaptcha