# server
server:
  port: 8501

# spring配置
spring:
  # Jackson转换数据时默认使用UTC时间,这样给前端返回的数据会和数据库差8小时,要和数据库时区保持一致
  # Asia/Shanghai=GMT+8,数据库url添加&serverTimeZone=Asia%2FShanghai或者&serverTimeZone=GMT%2B8
  jackson:
    time-zone: GMT+8
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Q-D37Sq*k61#yT_y
    # hikari详细配置(com.zaxxer.hikari.HikariConfig)
    hikari:
      pool-name: HikariPool  # 连接池名称
      connection-test-query: SELECT 1  # 自动检测连接
      connection-timeout: 30000  # 连接超时时间,默认30s
      maximum-pool-size: 10  # 最大连接数,默认10
      minimum-idle: 5  # 最小空闲连接数
      max-lifetime: 0  # 连接最大存活时间,0不过期,默认30min
      idle-timeout: 0  # 连接最大空闲时间,默认10min
  # redis
  data:
    redis:
      host: localhost
      port: 6379

# mybatis配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

# knife4j配置
springdoc:
  # 接口文档中类似queryVo={"provinceId":"1","cityId":"1"}这种参数不方便调试,可以将其扁平化
  default-flat-param-object: true

# 自定义配置
eshop:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/getCaptcha

  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: eshop-bucket