# server
server:
  port: 8514

spring:
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: Q-D37Sq*k61#yT_y
  # redis
  data:
    redis:
      host: localhost
      port: 6379

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml