# server
server:
  port: 8514

# spring
spring:
  # 微服务名称,会在nacos的服务列表中显示
  application:
    name: service-order
  # 微服务配置
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # openfeign
    openfeign:
      okhttp:
        enabled: true
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: Q-D37Sq*k61#yT_y
  # redis
  data:
    redis:
      host: localhost
      port: 6379

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml