# server
server:
  port: 8513

# spring
spring:
  # 服务名称
  application:
    name: service-cart
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis
  data:
    redis:
      host: localhost
      port: 6379