# server
server:
  port: 8513

# spring
spring:
  # 微服务名称,会在nacos的服务列表中显示
  application:
    name: service-cart
  # 微服务配置
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # openfeign
    openfeign:
      okhttp:
        enabled: true
  # redis
  data:
    redis:
      host: localhost
      port: 6379